actors:
  hiroaki.akanuma:
    image_url: /images/actors/hiroaki.akanuma.jpg
    name: Akanuma Hiroaki
    url: https://twitter.com/akanuma
  kozue.tabuchi:
    image_url: /images/actors/kozue.tabuchi.jpg
    name: Tabuchi Kozue
    url: https://www.facebook.com/profile.php?id=100015854472658
  yoko.tsuruoka:
    image_url: /images/actors/yoko.tsuruoka.jpg
    name: Tsuruoka Yoko
    url: https://twitter.com/tsuru_beer
  kenji.asano:
    image_url: /images/actors/kenji.asano.jpg
    name: Asano Kenji
    url: https://www.facebook.com/ijnekonasa
  kazuya.shida:
    image_url: /images/actors/kazuya.shida.jpg
    name: Shida Kazuya
    url:
  shizuka.kakimoto:
    image_url: /images/actors/shizuka.kakimoto.jpg
    name: Kakimoto Shizuka
    url: https://www.facebook.com/shizuka.kakimoto.9
  chen.zhao:
    image_url: /images/actors/chen.zhao.jpg
    name: Chen Zhao
    url: https://twitter.com/XY8080
  manabu.hosaka:
    image_url: /images/actors/manabu.hosaka.jpg
    name: Hosaka Manabu
    url:
  yuki.miyazaki:
    image_url: /images/actors/yuki.miyazaki.png
    name: Miyazaki Yuki
    url:
  masahiko.watanabe:
    image_url: /images/actors/masahiko.watanabe.jpg
    name: Watanabe Masahiko
    url: https://www.facebook.com/miracle.masapon
  ken.shimada:
    image_url: /images/actors/ken.shimada.png
    name: Shimada Ken
    url:
  megumi.saito:
    image_url: /images/actors/megumi.saito.jpg
    name: Saito Megumi
    url: https://www.facebook.com/hekoshabo
  ryusuke.homma:
    image_url: /images/actors/ryusuke.homma.jpg
    name: Homma Ryusuke
    url:
  tamaki.yogai:
    image_url: /images/actors/tamaki.yogai.png
    name: Yogai Tamaki
    url:
  azusa.nakayama:
    image_url: /images/actors/azusa.nakayama.jpg
    name: Nakayama Azusa
    url: https://instagram.com/azu.illust/
  yusuke.miyoshi:
    image_url: /images/actors/yusuke.miyoshi.jpg
    name: Miyoshi Yusuke
    url:
  kohei.morita:
    image_url: /images/actors/kohei.morita.png
    name: Morita Kohei
    url:
  shingo.suzuki:
    image_url: /images/actors/shingo.suzuki.jpg
    name: Suzuki Shingo
    url: https://twitter.com/mominosin
  robin.dickson:
    image_url: /images/actors/robin.dickson.jpg
    name: Robin Dickson
    url: https://twitter.com/rbndickson
  harvey.ico:
    image_url: /images/actors/harvey.ico.jpg
    name: Harvey Ico
    url:
  yutaro.tomoto:
    image_url: /images/actors/yutaro.tomoto.jpg
    name: Tomoto Yutaro
    url: https://twitter.com/YutaroTomoto
  keita.suzuki:
    image_url: /images/actors/keita.suzuki.jpg
    name: Suzuki Keita
    url:
  ayako.kiso:
    image_url: /images/actors/ayako.kiso.png
    name: Kiso Ayako
    url:
  shinichiro.suzuki:
    image_url: /images/actors/shinichiro.suzuki.jpg
    name: Suzuki Shinichiro
    url: https://twitter.com/shinisuz
  marino.yokoi:
    image_url: /images/actors/marino.yokoi.jpg
    name: Yokoi Marino
    url: https://twitter.com/rinoside
  hayato.miyoshi:
    image_url: /images/actors/hayato.miyoshi.jpg
    name: Miyoshi Hayato
    url: https://twitter.com/miyoshihayato
  kazumasa.kotaki:
    image_url: /images/actors/kazumasa.kotaki.jpg
    name: Kotaki Kazumasa
    url: https://www.facebook.com/kazumasa.kotaki.3
  mai.aiba:
    image_url: /images/actors/mai.aiba.jpg
    name: Aiba Mai
    url:
  naoto.watanabe:
    image_url: /images/actors/naoto.watanabe.jpg
    name: Watanabe Naoto
    url:
  kazuki.matsuda:
    image_url: /images/actors/kazuki.matsuda.jpg
    name: Matsuda Kazuki
    url: https://twitter.com/mats16k
  akihiro.tsukada:
    image_url: /images/actors/akihiro.tsukada.png
    name: Tsukada Akihiro
    url: https://twitter.com/akitsukada
  nobuyuki.yamaguchi:
    image_url: /images/actors/nobuyuki.yamaguchi.jpg
    name: Yamaguchi Nobuyuki
    url: https://twitter.com/nobuyama818
  takashi.yamamoto:
    image_url: /images/actors/takashi.yamamoto.jpg
    name: Yamamoto Takashi
    url: https://twitter.com/taka4yamamoto
author: UniFa
description: UniFa 開発メンバーが社内での開発の様子やサービス、参加したイベント、<br/>技術トピックなどについてゆるく話していく Podcast です。
description_long: UniFa 開発メンバーが社内での開発の様子やサービス、参加したイベント、技術トピックなどについてゆるく話していく Podcast
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: unifa_dev
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: UniFa Developer's Podcast
url: http://tech.unifa-e.com
