actors:
  hiroaki.akanuma:
    image_url: /images/actors/hiroaki.akanuma.jpg
    name: Akanuma Hiroaki
    url: https://twitter.com/akanuma
  kozue.tabuchi:
    image_url: /images/actors/kozue.tabuchi.jpg
    name: Tabuchi Kozue
    url: https://www.facebook.com/profile.php?id=100015854472658
  yoko.tsuruoka:
    image_url: /images/actors/yoko.tsuruoka.jpg
    name: Tsuruoka Yoko
    url: https://twitter.com/tsuru_beer
  kenji.asano:
    image_url: /images/actors/kenji.asano.jpg
    name: Asano Kenji
    url: https://www.facebook.com/ijnekonasa
  kazuya.shida:
    image_url: /images/actors/kazuya.shida.jpg
    name: Shida Kazuya
    url:
  shizuka.kakimoto:
    image_url: /images/actors/shizuka.kakimoto.jpg
    name: Kakimoto Shizuka
    url: https://www.facebook.com/shizuka.kakimoto.9
  chen.zhao:
    image_url: /images/actors/chen.zhao.jpg
    name: Chen Zhao
    url: https://twitter.com/XY8080
  manabu.hosaka:
    image_url: /images/actors/manabu.hosaka.jpg
    name: Hosaka Manabu
    url:
  yuki.miyazaki:
    image_url: /images/actors/yuki.miyazaki.png
    name: Miyazaki Yuki
    url:
  masahiko.watanabe:
    image_url: /images/actors/masahiko.watanabe.jpg
    name: Watanabe Masahiko
    url: https://www.facebook.com/miracle.masapon
  ken.shimada:
    image_url: /images/actors/ken.shimada.png
    name: Shimada Ken
    url:
  megumi.saito:
    image_url: /images/actors/megumi.saito.jpg
    name: Saito Megumi
    url: https://www.facebook.com/hekoshabo
  ryusuke.homma:
    image_url: /images/actors/ryusuke.homma.jpg
    name: Homma Rysuke
    url:
  tamaki.yogai:
    image_url: /images/actors/tamaki.yogai.png
    name: Yogai Tamaki
    url:
author: UniFa
description: UniFa 開発メンバーが社内での開発の様子やサービス、参加したイベント、<br/>技術トピックなどについてゆるく話していく Podcast です。
description_long: UniFa 開発メンバーが社内での開発の様子やサービス、参加したイベント、技術トピックなどについてゆるく話していく Podcast
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: unifa_dev
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: UniFa Developer's Podcast
url: http://tech.unifa-e.com
